### ISSUE TITLE
Sample IAM policy for the action?

### ISSUE THREAD

**Issue by VictorioBerra** [chetan/invalidate-cloudfront-action#1]
Thanks for building this action.

I was wondering if you could share the minimum policy needed for the action.

For example, is this all that would be needed?

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ChetanInvalidateCFPolicy1",
            "Effect": "Allow",
            "Action": "cloudfront:CreateInvalidation",
            "Resource": "arn:aws:cloudfront::REDACTED:distribution/REDACTED"
        }
    ]
}
```

**Comment by chetan** [comment]
I actually don't have a policy for just this action, but that looks right. You'll probably need to add access for writing to S3 as well, since that usually goes together.

**Comment by VictorioBerra** [comment]
For future reference if anyone finds this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "cloudfront:CreateInvalidation",
            "Resource": "arn:aws:cloudfront::REDACTED:distribution/*"
        }
    ]
}
```

You can not specify a specific distro. This saved me time: https://stackoverflow.com/a/44373795/1777780

**Comment by chetan** [comment]
Thanks! I will add this to the README
