### ISSUE TITLE
allow OIDC instead of keys

### ISSUE THREAD

**Issue by exussum12** [chetan/invalidate-cloudfront-action#12]
Github supports open id connect to get credentials from AWS, This repo rejects anything which does not pass though the AWS creds.

Could OIDC support be added?

**Comment by forensicmike** [comment]
@exussum12 thought id let you know that i decided to fork this to see if I could get it working. after gutting a few things, it seems to work by simply removing the parameters. **note**: i do not recommend pointing to my fork, but you could always do the same until the real one is fixed :)

https://github.com/forensicmike/invalidate-cloudfront-action/commit/911f19b46b0c74320d8477ad08743eacb750b38f

**Comment by chetan** [comment]
Looks good and thanks for experimenting and confirming it works @forensicmike. I'll try to get it implemented as an option soon.

**Comment by forensicmike** [comment]
I did a bit more experimenting and wanted to share what I found about how the aws-actions/configure-aws-credentials@v1 action works, which is the recommended way to implement the OIDC connectivity.

it appears that after successfully completing, every step afterwards on that same job will automatically include the following (it shows up in the action runner output):
```  env:
    AWS_DEFAULT_REGION: ca-central-1
    AWS_REGION: ca-central-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***```

**Comment by exussum12** [comment]
@forensicmike  yeah I ended up just writing a simple script when I couldn't find a preexisting action 

https://github.com/SykesCottages/technology-blog/blob/master/.github/workflows/deploy.yml#L30

Probably needed some docs adding too about adding

```
permissions:
      id-token: write
      contents: read
```

Thanks for looking!

**Comment by chetan** [comment]
Great, thanks. Will definitely be easier to leverage that action to set things up.

**Comment by forensicmike** [comment]
Yeah, that caught me as well. Also think there needs to be a bit more more fanfare around the need to manually setup the trust policy in AWS lest any repo on Github can assume that role if they possess the role ARN..

**Comment by johnmcase** [comment]
@chetan Sorry to revive such and old issue, but why is this marked as completed?

If I'm understanding correctly, this action will still fail if the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` inputs are not supplied:  https://github.com/chetan/invalidate-cloudfront-action/blob/c384d5f09592318a77b1e5c0c8d4772317e48b25/entrypoint.sh#L19

The fork @forensicmike made removed the checks for those parameters and presumed that the caller had already called the `aws-actions/configure-aws-credentials` action prior to calling this one.

What am I missing?

**Comment by chetan** [comment]
@johnmcase successfully running the `aws-actions/configure-aws-credentials` action passes those variables to this action, as [documented in the readme](https://github.com/chetan/invalidate-cloudfront-action?tab=readme-ov-file#aws-credentials). 

If you're seeing an issue than you may need to look into the output of that action to see what's going on. You can refer to the readme in this repo and the [test action](https://github.com/chetan/invalidate-cloudfront-action/blob/develop/.github/workflows/tests.yml) for some more examples.
