### ISSUE TITLE
PATHS to all files

### ISSUE THREAD

**Issue by jakcst** [chetan/invalidate-cloudfront-action#17]
I'm trying to create an invalidation to refresh all files in an s3 bucket. 
I can't seem to figure out why I am getting this message:

```
*** Reading PATHS from /*
PATHS file not found. nothing to do. exiting
```

`uses: chetan/invalidate-cloudfront-action@v2`

**Comment by chetan** [comment]
@jakcst looks like I have a typo in the error message. It should say `PATHS_FROM file not found. nothing to do. exiting`. If you are trying to pass a wildcard, you are using the wrong env var config. You should be setting `PATHS=/*` instead.

**Comment by jakcst** [comment]
Thank you for the quick response! Here is the snippet from my yaml file. Maybe I am doing something incorrectly?

`    - name: Create a CloudFront invalidation
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        PATHS_FROM: '/*'
        AWS_REGION: 'us-east-1'
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}`

**Comment by chetan** [comment]
Yes, the 'PATHS_FROM' variable is meant to point to a file which contains a
list of files to invalidate. Change that to 'PATHS' and it should work!

**Comment by jakcst** [comment]
Got it. Many thanks!
