### ISSUE TITLE
wget: command not found

### ISSUE THREAD

**Issue by es-fabricemarie** [chetan/invalidate-cloudfront-action#19]
When using `chetan/invalidate-cloudfront-action@v2` on GitHub, we now get the error:

```
Run chetan/invalidate-cloudfront-action@v2
Run $GITHUB_ACTION_PATH/entrypoint.sh
/home/fedora/runner/_work/_actions/chetan/invalidate-cloudfront-action/v2/entrypoint.sh: line 56: wget: command not found
Error: Process completed with exit code 127.
```

Culprit seems to be:
https://github.com/chetan/invalidate-cloudfront-action/commit/74a68bb493a1022d52af8a4f26ce74103c3daf2f#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R70

Hope this helps.

**Comment by chetan** [comment]
@es-fabricemarie, can you tell me how you are running the action? Are you using a custom runner by any chance?

**Comment by es-fabricemarie** [comment]
Hi yes, the team is using self-hosted Github Runner for this project, my bad. I thought this one was running GitHub hosted.. Thanks.
