### ISSUE TITLE
I am a little confused about why chetan/git-restore-mtime-action is needed.

### ISSUE THREAD

**Issue by VictorioBerra** [chetan/invalidate-cloudfront-action#2]
I am not using GitHub Pages, I generate my VueJS SPA and I just deploy that right to S3 and then I need to invalidate CF.

Do you only use git-restore-mtime-action because you use peaceiris/actions-gh-pages? Would I need that as well?

Thanks.

**Comment by VictorioBerra** [comment]
I think maybe im understanding a bit better now... you are actually using GitHub Pages as a "trick/hack" to bump the timestamp of only changed files from dist, that was S3 and the invalidation plugin can upload and invalidate only whats changed. Right? Because you host on S3/CF, you dont do anything with GitHub Pages.

**Comment by chetan** [comment]
Almost right. I'm actually deploying to both GitHub pages and S3 and the two actions are not related. 

The __restore-mtime__  action is simply to avoid uploading unchanged files to S3 as the `sync` command uses these timestamps to look for changes. 

Only the paths you give in the configuration are invalidated, so this has nothing to do with timestamps either, though in theory, it could, I suppose. I'm also using this with a VueJS SPA so all assets other than `index.html` get unique filenames when the contents change and don't require invalidation. If you have other assets that change [frequently], then you may want to invalidate those as well.

**Comment by VictorioBerra** [comment]
@chetan 

Thanks for the quick reply. I was up late thinking about this lol

> all assets other than index.html get unique filenames when the contents change and **don't require invalidation.**

Why do they not require invalidation? Does S3/CF automatically invalidate deleted files or something?

I use Nuxt so my changed bundles also get unique file names. I thought for some reason I still had to tell CF to invalidate.

**Comment by chetan** [comment]
The idea behind invalidation is that when your browser (or other client) makes a request to the CDN for a particular asset, say `foo-somehash.js`, the CDN (cloudfront in this case) by default will serve from its local cache, if available. 

If you then change that asset, there will be a period of time where the stale asset is being served. To avoid this, we force invalidation.

In the case of bundlers which generate unique names, after a deploy, your browser will request `foo-somehash2.js` which will be a cache miss on the CDN, forcing it to go back to the origin (S3 in this case) for the resource.

As for deleted files, they will eventually fall out of the cache when they are no longer requested. I don't think there's any need to explicitly invalidate them.

**Comment by VictorioBerra** [comment]
Ah right because index.html is asking for stuff not in CF... duh. Thanks!!
