### ISSUE TITLE
Unknown output type: aws_region 

### ISSUE THREAD

**Issue by tuwid** [chetan/invalidate-cloudfront-action#20]
Run chetan/invalidate-cloudfront-action@master
  env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    GLOBAL_DOTENV_FILE_NAME: xxxxxx-global.env
    SERVICE_NAME: xxxxxxx
    ENV_NAME: xxxxxxxx
    BRAND: xxxxxxx
    BRANCH_NAME: 
    IMAGE_TAG: xxxxxx
    KNOWN_HOSTS: github.com ssh-rsa xxxxxxxxx
    DIST_DIR: dist
    DISTRIBUTION: xxxxxxxxxx
    PATHS: /*
    AWS_REGION: eu-north-1
    AWS_ACCESS_KEY_ID: xxxxxxxxx
    AWS_SECRET_ACCESS_KEY: ***

Getting this weird at the end: 
`Unknown output type: eu-north-1` 

Could it be due to formatting of one of the envs ?

**Comment by chetan** [comment]
Please try again on the develop branch or V2 tag

**Comment by tuwid** [comment]
Apparently it was a + or something like that in the secret. After removing that and moving to v2 its working
