### ISSUE TITLE
Why is region required?

### ISSUE THREAD

**Issue by aychtang** [chetan/invalidate-cloudfront-action#7]
Hi @chetan, just wondering why the aws region is required as cloudfront is a global resource? I see `AWS_REGION` is checked in the entrypoint.sh script which seemed to be used for the initial `aws configure` command, but is that necessary for this script?

**Comment by chetan** [comment]
Hi @aychtang, the region is used for setting up the aws profile as you noted. It is required by the cloudfront API (I don't have a reference handy, sorry). Hope that helps!

**Comment by chetan** [comment]
I think it may just be to target the region-specific API endpoint 

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-region
