### ISSUE TITLE
Only works for linux workflows

### ISSUE THREAD

**Issue by hognevevle** [chetan/invalidate-cloudfront-action#9]
Action does not work for non-linux agents, such as `mac-latest` or `windows-latest`:

```
Run chetan/invalidate-cloudfront-action@master
Error: Container action is only supported on Linux
```

**Comment by chetan** [comment]
@hognevevle thanks for the report. Since this action currently relies on Docker it sounds like the only fix is to rewrite it without containers. I may take a crack at that when I've got some time, especially since the upstream Docker Hub changes are less than friendly.

**Comment by chetan** [comment]
@hognevevle I just cut a v2 release which should take care of this.  Let me know if you run into any issues with it!
